formatter: "markdown table"

sections:
  show:
    - modules
    - resources
    - inputs
    # - outputs

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

sort:
  enabled: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

content: |-
  {{- if .Config.Sections.ModuleCalls -}}
    {{- if not .Module.ModuleCalls -}}
      {{- if not .Config.Settings.HideEmpty -}}
        {{- indent 0 "#" }} Modules

  No modules.
      {{- end }}
    {{ else }}
      {{- indent 0 "#" }} Modules

  | Name | Source | Version |
  |------|--------|---------|
      {{- range .Module.ModuleCalls }}
  | {{ anchorNameMarkdown "module" .Name }} | {{ .Source }} | {{ .Version | default "n/a" }} |
      {{- end }}
    {{ end }}
  {{ end -}}
  {{- if or .Config.Sections.Resources .Config.Sections.DataSources -}}
    {{- if not .Module.Resources -}}
      {{- if not .Config.Settings.HideEmpty -}}
        {{- indent 0 "#" }} Resources

        No resources.
      {{ end }}
    {{ else }}
      {{- indent 0 "#" }} Resources

  | Name | Type |
  |------|------|
      {{- range .Module.Resources }}
        {{- $isResource := and $.Config.Sections.Resources ( eq "resource" (printf "%s" .GetMode)) }}
        {{- $isDataResource := and $.Config.Sections.DataSources ( eq "data source" (printf "%s" .GetMode)) }}
        {{- if or $isResource $isDataResource }}
          {{- $fullspec := ternary .URL (printf "[%s](%s)" .Spec .URL) .Spec }}
  | {{ $fullspec }} | {{ .GetMode }} |
        {{- end }}
      {{- end }}
    {{ end }}
  {{ end -}}
  {{- if .Config.Sections.Inputs -}}
    {{- if not .Module.Inputs -}}
      {{- if not .Config.Settings.HideEmpty -}}
        {{- indent 0 "#" }} Inputs

  No inputs.
      {{- end }}
    {{ else }}
        {{- indent 0 "#" }} Inputs

  Here are the input variables of the module:

  | Name | Description |
        {{- if .Config.Settings.Type }} Type |{{ end }}
        {{- if .Config.Settings.Default }} Default |{{ end }}
        {{- if .Config.Settings.Required }} Required |{{ end }}
  |------|-------------|
        {{- if .Config.Settings.Type }}------|{{ end }}
        {{- if .Config.Settings.Default }}---------|{{ end }}
        {{- if .Config.Settings.Required }}:--------:|{{ end }}
        {{- range .Module.Inputs }}
  | {{ anchorNameMarkdown "input" .Name }} | {{ tostring .Description | sanitizeMarkdownTbl }} |
          {{- if $.Config.Settings.Type -}}
            {{- if hasPrefix "object({" (tostring .Type | sanitizeMarkdownTbl) -}}
              {{ printf " <pre>" }}{{ tostring .Type | sanitizeMarkdownTbl }}{{ printf "</pre>" }} |
            {{- else if hasPrefix "list(object({" (tostring .Type | sanitizeMarkdownTbl) -}}
              {{ printf " <pre>" }}{{ tostring .Type | sanitizeMarkdownTbl }}{{ printf "</pre>" }} |
            {{- else if hasPrefix "map(object({" (tostring .Type | sanitizeMarkdownTbl) -}}
              {{ printf " <pre>" }}{{ tostring .Type | sanitizeMarkdownTbl }}{{ printf "</pre>" }} |
            {{- else -}}
              {{ printf " `" }}{{ tostring .Type | sanitizeMarkdownTbl }}{{ printf "`" }} |
            {{- end -}}
          {{- end -}}
          {{- if $.Config.Settings.Default -}}
            {{- if eq (.GetValue | sanitizeMarkdownTbl) "{}" -}}
              {{ printf " `" }}{{ .GetValue | sanitizeMarkdownTbl }}{{ printf "`" }} |
            {{- else if hasPrefix "{" (.GetValue | sanitizeMarkdownTbl) -}}
              {{ printf " <pre>" }}{{ .GetValue | sanitizeMarkdownTbl }}{{ printf "</pre>" }} |
            {{- else -}}
              {{ printf " `" }}{{ .GetValue | sanitizeMarkdownTbl }}{{ printf "`" }} |
            {{- end -}}
          {{- end -}}
          {{- if $.Config.Settings.Required -}}
            {{ printf " " }}{{ ternary .Required "$\\color{green}{yes}$" "$\\color{red}{no}$" }} |
          {{- end -}}
        {{- end }}
    {{ end }}
  {{ end -}}
  {{- if .Config.Sections.Outputs -}}
    {{- if not .Module.Outputs -}}
      {{- if not .Config.Settings.HideEmpty -}}
        {{- indent 0 "#" }} Outputs

        No outputs.
      {{- end }}
    {{ else }}
      {{- indent 0 "#" }} Outputs

  | Name | Description |
  |------|-------------|
      {{- range .Module.Outputs }}
  | {{ anchorNameMarkdown "output" .Name }} | {{ tostring .Description | sanitizeMarkdownTbl }} |
      {{- end }}
    {{ end }}
  {{ end -}}
